# Site settings
title: Pepyn Swagemakers
email: ps222nq@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
Portfolio site for the 1DV022 Course at Linnaeus University, by Pepyn Swagemakers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: PepynS
github_username:  ps222nq

# Build settings
markdown: kramdown
